services:
  arm-controller:
    build: .
    container_name: arm-controller
    restart: unless-stopped
    privileged: true
    init: true

    devices:
      - /dev/input:/dev/input
      - /dev/bus/usb:/dev/bus/usb

    volumes:
      - ./arm_gamepad.py:/app/arm_gamepad.py:ro
      # expose stable symlink dirs inside container
      - /dev/input/by-id:/dev/input/by-id:ro
      - /dev/input/by-path:/dev/input/by-path:ro

    environment:
      - PYTHONUNBUFFERED=1
      - GAMEPAD_DEV=/dev/input/by-id/usb-8BitDo_8BitDo_Ultimate_2C_Wireless_Controller_02E29EA491-event-joystick